# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PackageManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PackageManager

  pod 'Kingfisher', '~> 5.0'
  pod 'CardScanner'
  target 'PackageManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PackageManagerUITests' do
    # Pods for testing
  end

end
